// Wallet Balances Component
// Generated by Cradle

'use client';

import { useWalletBalances, usePortfolioValue } from '@/hooks/useWalletBalances';

interface WalletBalancesProps {
  address?: string;
  blockchain?: string;
  className?: string;
}

export function WalletBalances({ address, blockchain, className }: WalletBalancesProps) {
  const { balances, totalValue, isLoading, error } = usePortfolioValue({ address, blockchain });

  if (isLoading) {
    return (
      <div className={`p-4 rounded-xl bg-zinc-800/50 border border-zinc-700/50 ${className}`}>
        <div className="animate-pulse space-y-3">
          <div className="h-6 bg-zinc-700 rounded w-1/3" />
          <div className="h-4 bg-zinc-700 rounded w-full" />
          <div className="h-4 bg-zinc-700 rounded w-2/3" />
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className={`p-4 rounded-xl bg-zinc-800/50 border border-red-500/30 ${className}`}>
        <p className="text-red-400 text-sm">Failed to load balances</p>
      </div>
    );
  }

  return (
    <div className={`p-4 rounded-xl bg-zinc-800/50 border border-zinc-700/50 ${className}`}>
      <div className="flex items-center justify-between mb-4">
        <h3 className="text-sm font-medium text-zinc-400">Portfolio Value</h3>
        <span className="text-lg font-bold text-white">
          ${totalValue.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
        </span>
      </div>
      <div className="space-y-2">
        {balances?.slice(0, 5).map((balance, i) => (
          <div key={i} className="flex items-center justify-between text-sm">
            <span className="text-zinc-300">{balance.symbol}</span>
            <span className="text-zinc-400">
              ${balance.value_usd.toLocaleString(undefined, { minimumFractionDigits: 2 })}
            </span>
          </div>
        ))}
        {balances && balances.length > 5 && (
          <p className="text-xs text-zinc-500 text-center pt-2">
            +{balances.length - 5} more tokens
          </p>
        )}
      </div>
    </div>
  );
}

export default WalletBalances;