// Wallet Balances Hook
// Generated by Cradle

'use client';

import { useQuery } from '@tanstack/react-query';
import { useAccount } from 'wagmi';
import { duneClient, type WalletBalance } from '@/lib/dune-client';

export interface UseWalletBalancesParams {
  address?: string;
  blockchain?: string;
  minBalanceUsd?: number;
  enabled?: boolean;
}

export function useWalletBalances(params?: UseWalletBalancesParams) {
  const { address: connectedAddress } = useAccount();
  const targetAddress = params?.address ?? connectedAddress;

  return useQuery({
    queryKey: ['dune-wallet-balances', targetAddress, params?.blockchain, params?.minBalanceUsd],
    queryFn: () => duneClient.getWalletBalances(
      targetAddress!,
      params?.blockchain ?? 'arbitrum',
      params?.minBalanceUsd ?? 1
    ),
    enabled: !!targetAddress && (params?.enabled ?? true),
    staleTime: 60000,
  });
}

export function usePortfolioValue(params?: UseWalletBalancesParams) {
  const { data: balances, ...rest } = useWalletBalances(params);
  
  const totalValue = balances?.reduce((sum, b) => sum + b.value_usd, 0) ?? 0;

  return {
    ...rest,
    balances,
    totalValue,
  };
}