// x402 Payment API Server
// Generated by Cradle

import Fastify from 'fastify';
import cors from '@fastify/cors';
import { paymentMiddleware } from './middleware';

const fastify = Fastify({
  logger: true,
});

// Register plugins
fastify.register(cors, {
  origin: true,
  methods: ['GET', 'POST', 'PUT', 'DELETE'],
  allowedHeaders: ['Content-Type', 'X-Payment-Receipt'],
  exposedHeaders: [
    'X-Payment-Address',
    'X-Payment-Amount',
    'X-Payment-Currency',
    'X-Payment-Chain-ID',
    'X-Payment-Timeout',
  ],
});

// Register payment middleware
fastify.register(paymentMiddleware);

// Protected resource endpoint
fastify.get('/api/premium/resource', async (request, reply) => {
  // At this point, payment has been verified by middleware
  const receipt = (request as any).paymentReceipt;

  return {
    success: true,
    message: 'Access granted to premium resource',
    data: {
      // Your premium content here
      content: 'This is the premium content you paid for',
      accessedAt: new Date().toISOString(),
      paidWith: receipt?.txHash,
    },
  };
});

// Health check endpoint
fastify.get('/health', async () => {
  return { status: 'ok', timestamp: new Date().toISOString() };
});

// Payment info endpoint
fastify.get('/api/payment-info', async () => {
  return {
    resource: '/api/premium/resource',
    price: '1000000000000000',
    currency: 'ETH',
    chainId: parseInt(process.env.CHAIN_ID || '421614'),
    timeout: 300,
    receiverAddress: process.env.PAYMENT_RECEIVER_ADDRESS,
  };
});

// Start server
const start = async () => {
  try {
    const port = parseInt(process.env.PORT || '3001');
    await fastify.listen({ port, host: '0.0.0.0' });
    console.log(`Payment API server running on port ${port}`);
  } catch (err) {
    fastify.log.error(err);
    process.exit(1);
  }
};

start();