openapi: '3.1.0'
info:
  title: x402 Payment API
  version: '1.0.0'
  description: |
    API with x402 protocol support for HTTP-native payments.
    
    ## Payment Flow
    1. Request the protected resource
    2. Receive 402 with payment requirements in headers
    3. Submit payment on-chain
    4. Retry request with X-Payment-Receipt header

servers:
  - url: http://localhost:3001
    description: Development server

paths:
  /api/premium/resource:
    get:
      summary: Access premium resource
      description: Protected resource requiring x402 payment
      operationId: getPremiumResource
      parameters:
        - name: X-Payment-Receipt
          in: header
          required: false
          description: Base64-encoded payment receipt
          schema:
            type: string
      responses:
        '200':
          description: Access granted
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
        '402':
          description: Payment required
          headers:
            X-Payment-Address:
              schema:
                type: string
              description: Address to send payment to
            X-Payment-Amount:
              schema:
                type: string
              description: Payment amount in wei
            X-Payment-Currency:
              schema:
                type: string
                enum: [ETH, USDC, USDT, DAI, CUSTOM]
            X-Payment-Chain-ID:
              schema:
                type: string
              description: Blockchain chain ID
            X-Payment-Timeout:
              schema:
                type: string
              description: Receipt validity window in seconds
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentRequired'

  /api/payment-info:
    get:
      summary: Get payment information
      operationId: getPaymentInfo
      responses:
        '200':
          description: Payment configuration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentInfo'

  /health:
    get:
      summary: Health check
      operationId: healthCheck
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  timestamp:
                    type: string
                    format: date-time

components:
  schemas:
    PaymentRequired:
      type: object
      properties:
        error:
          type: string
        message:
          type: string
        requirements:
          $ref: '#/components/schemas/PaymentRequirements'

    PaymentRequirements:
      type: object
      properties:
        address:
          type: string
          description: Payment receiver address
        amount:
          type: string
          description: Payment amount in wei
          example: '1000000000000000'
        currency:
          type: string
          enum: [ETH, USDC, USDT, DAI, CUSTOM]
          example: 'ETH'
        chainId:
          type: integer
          example: 421614
        timeout:
          type: integer
          description: Receipt validity in seconds
          example: 300

    PaymentInfo:
      type: object
      properties:
        resource:
          type: string
        price:
          type: string
        currency:
          type: string
        chainId:
          type: integer
        timeout:
          type: integer
        receiverAddress:
          type: string

    PaymentReceipt:
      type: object
      required:
        - txHash
        - blockNumber
        - from
        - to
        - amount
        - timestamp
      properties:
        txHash:
          type: string
          description: Transaction hash
        blockNumber:
          type: integer
          description: Block number
        from:
          type: string
          description: Sender address
        to:
          type: string
          description: Receiver address
        amount:
          type: string
          description: Amount in wei
        timestamp:
          type: integer
          description: Unix timestamp
        chainId:
          type: integer
          description: Chain ID