// x402 Payment Types
// Generated by Cradle

export interface PaymentReceipt {
  txHash: string;
  blockNumber: number;
  from: string;
  to: string;
  amount: string;
  timestamp: number;
  chainId: number;
}

export interface PaymentRequirements {
  address: string;
  amount: string;
  currency: 'ETH';
  chainId: number;
  timeout: number;
  
}

export interface X402Headers {
  'X-Payment-Address': string;
  'X-Payment-Amount': string;
  'X-Payment-Currency': string;
  'X-Payment-Chain-ID': string;
  'X-Payment-Timeout': string;
  
}

export interface PaymentVerificationResult {
  valid: boolean;
  error?: string;
  receipt?: PaymentReceipt;
}

export function createPaymentRequiredHeaders(requirements: PaymentRequirements): X402Headers {
  return {
    'X-Payment-Address': requirements.address,
    'X-Payment-Amount': requirements.amount,
    'X-Payment-Currency': requirements.currency,
    'X-Payment-Chain-ID': String(requirements.chainId),
    'X-Payment-Timeout': String(requirements.timeout),
    
  };
}

export function parsePaymentReceipt(encoded: string): PaymentReceipt | null {
  try {
    const decoded = Buffer.from(encoded, 'base64').toString('utf-8');
    const receipt = JSON.parse(decoded) as PaymentReceipt;
    
    // Basic validation
    if (!receipt.txHash || !receipt.from || !receipt.to || !receipt.amount) {
      return null;
    }
    
    return receipt;
  } catch {
    return null;
  }
}

export function encodePaymentReceipt(receipt: PaymentReceipt): string {
  return Buffer.from(JSON.stringify(receipt)).toString('base64');
}